Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - spec/**/*