require 'barr/version'
require 'barr/manager'
require 'barr/block'
require 'barr/controller'

require 'barr/blocks/battery'
require 'barr/blocks/bbc_weather'
require 'barr/blocks/bspwm'
require 'barr/blocks/clock'
require 'barr/blocks/conky'
require 'barr/blocks/cpu'
require 'barr/blocks/free_text'
require 'barr/blocks/hdd'
require 'barr/blocks/http_grab'
require 'barr/blocks/hue_light'
require 'barr/blocks/hue_group'
require 'barr/blocks/i3'
require 'barr/blocks/ip'
require 'barr/blocks/mem'
require 'barr/blocks/playerctl'
require 'barr/blocks/processes'
require 'barr/blocks/rhythmbox'
require 'barr/blocks/mpd'
require 'barr/blocks/temperature'
require 'barr/blocks/whoami'
require 'barr/blocks/separator'

require 'barr/controllers/bbc_weather'
require 'barr/controllers/http_grab'
require 'barr/controllers/playerctl'

module Barr
end
